# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: VMR
email: vandersonmr2@gmail.com
description: I am a M.Sc. Student at State University of Campinas where I am investigating techniques to detect performance issues in Virtual Machines, JIT Compilers and Compilers in general. My research is currently being developed at the Multidisciplinary High Performance Computing Lab.
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site
twitter_username: vandersonmr_
github_username:  vandersonmr

# Build settings
markdown: kramdown
